AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Deployment CCBD Assignment 2
Resources:
  A2LF0CORS:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: A2_LF0
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./lambda_functions/LF0
      Description: 'CCBD Assignment: Lambda function for CORS'
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::958611120422:role/service-role/A2-LF0-CORS-role-qavwwkmv'
      Events:
        CCBD_Photo_Album:
          Type: Api
          Properties:
            StageName: Dev
            Path: /search
            Method: OPTIONS
        CCBD_Photo_Album:
          Type: Api
          Properties:
            StageName: Dev
            Path: /upload/{folder}/{sub-folder}/{object}
            Method: OPTIONS
